# Generated by Django 3.0.7 on 2021-07-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210714_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_orders', to='foodcartapp.Product', verbose_name='товар'),
        ),
    ]
